image:
  name: gitlab.sc.lan:5001/korhal/docker/docker-builder:latest

stages:
  - build

variables:
  CORE_COMMIT_HASH: "HEAD"    # SHA Hash of the commit to use as the Core source.
  DB_COMMIT_HASH: "HEAD"      # SHA Hash of the commit to use as database source.

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export tag=":latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        export tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "Building Database ..."
    - cd cmangos_db
    - docker build -t gitlab.sc.lan:5001/korhal/cmangos-docker/db${tag} --no-cache --build-arg CORE_COMMIT_HASH --build-arg DB_COMMIT_HASH .
    - docker push gitlab.sc.lan:5001/korhal/cmangos-docker/db${tag}
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/db${tag}
    - echo "Building Game Server ..."
    - cd ../cmangos_mangosd/
    - docker build -t gitlab.sc.lan:5001/korhal/cmangos-docker/mangosd${tag} --no-cache --build-arg CORE_COMMIT_HASH --build-arg DB_COMMIT_HASH .
    - docker push gitlab.sc.lan:5001/korhal/cmangos-docker/mangosd${tag}
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/mangosd${tag}
    - echo "Building Login Server ..."
    - cd ../cmangos_realmd/
    - docker build -t gitlab.sc.lan:5001/korhal/cmangos-docker/realmd${tag} --no-cache --build-arg CORE_COMMIT_HASH --build-arg DB_COMMIT_HASH .
    - docker push gitlab.sc.lan:5001/korhal/cmangos-docker/realmd${tag}
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/realmd${tag}
    - cd ..
    - echo "Cleaning up images ..."
    - docker image prune -f
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - linux
    - docker
    - dind
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web") && ($CI_COMMIT_BRANCH == "wotlk" || $CI_COMMIT_BRANCH == "stable")