image:
  name: gitlab.sc.lan:5001/korhal/docker/docker-builder:latest

stages:
  - build

variables:
  DB_COMMIT_HASH: "not-yet-used"
  CORE_COMMIT_HASH: "not-yet-used"

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker-compose build --no-cache
    - docker-compose push
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/db:latest
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/mangosd:latest
    - docker rmi gitlab.sc.lan:5001/korhal/cmangos-docker/realmd:latest
    - docker image prune -f
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - linux
    - docker
    - dind
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_BRANCH == "wotlk"