version: "3"

volumes:
  db:
  mangosd_etc:
  realmd_etc:

services:
  cmangos_db:
    build:
      context: ./cmangos_db/
      dockerfile: Dockerfile
    image: cmangos_db:latest
    networks:
      cmangos-wotlk:
        aliases:
          - database
    volumes:
      - db:/var/lib/mysql
      - ./cmangos_db:/docker-entrypoint-initdb.d:ro
    restart: "unless-stopped"
    environment:
      - TZ=Europe/Amsterdam
      - MYSQL_ROOT_PASSWORD=mangos

  cmangos_mangosd:
    build:
      context: ./cmangos_mangosd/
      dockerfile: Dockerfile
    image: cmangos_mangosd:latest
    depends_on:
      - cmangos_db
    networks:
      - cmangos-wotlk
    ports:
      - 8085:8085
      - 3443:3443
      - 7878:7878
    volumes:
      - mangosd_etc:/opt/cmangos/etc
      - "/opt/cmangos-data:/opt/cmangos-data:ro"
    restart: "unless-stopped"
    environment:
      - TZ=Europe/Amsterdam
      - CHARACTERS_DB=wotlkcharacters
      - MANGOSD_DB=wotlkmangos
      - REALMD_DB=wotlkrealmd
      - DB_USER=mangos
      - DB_PASS=mangos
      - REALMD_USER=mangos
      - REALMD_PASS=mangos
      - DB_SERVER=database
      - REALMD_SERVER=database

  cmangos_realmd:
    build:
      context: ./cmangos_realmd/
      dockerfile: Dockerfile
    image: cmangos_realmd:latest
    depends_on:
      - cmangos_db
    networks:
      - cmangos-wotlk
    ports:
      - 3724:3724
    volumes:
      - realmd_etc:/opt/cmangos/etc
    restart: "unless-stopped"
    environment:
      - TZ=Europe/Amsterdam
      - REALMD_DB=wotlkrealmd
      - DB_USER=mangos
      - DB_PASS=mangos
      - DB_SERVER=database

networks:
  cmangos-wotlk: