version: "3"

volumes:
  cmangos_db:
  cmangos_mangosd_logs:
  cmangos_mangosd_etc:
  cmangos_realmd_etc:

services:
  cmangos_db:
    build:
      context: ./cmangos_db/
      dockerfile: Dockerfile
    image: cmangos_db:0.11
    networks:
      - cmangos-net
    ports:
      - 3306:3306
    volumes:
      - cmangos_db:/var/lib/mysql
      - ./cmangos_db:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mangos

  cmangos_mangosd:
    build:
      context: ./cmangos_mangosd/
      dockerfile: Dockerfile
    image: cmangos_mangosd:0.11
    depends_on:
      - cmangos_db
    links:
      - "cmangos_db:database"
    networks:
      - cmangos-net
    ports:
      - 8085:8085
      - 3443:3443
      - 7878:7878
    volumes:
      - cmangos_mangosd_etc:/opt/cmangos/etc
      - cmangos_mangosd_logs:/opt/cmangos/logs
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam

  cmangos_realmd:
    build:
      context: ./cmangos_realmd/
      dockerfile: Dockerfile
    image: cmangos_realmd:0.11
    depends_on:
      - cmangos_db
    links:
      - "cmangos_db:database"
    networks:
      - cmangos-net
    ports:
      - 3724:3724
    volumes:
      - cmangos_realmd_etc:/opt/cmangos/etc
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam

networks:
  cmangos-net:
