version: "3.5"

networks:
  default:
    external:
      name: mangos_backend

services:
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    restart: always
    ports:
      - '42069:80'
    environment:
       PMA_HOST: "database"